### ISSUE TITLE
Rollover Cmo-Argos and DMP Data Repositories 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1006]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
cmo-argos/dmp repos pointing to dmp-2023 and cmo-argos history wiped

**Comment by sheridancbio** [comment]
dmp-2023 and dmp-private-2023 have been created and populated with the initial commits from the start of this year. The symlinks have been adjusted and we are running on these new repos/clones now for the production dmp imports.

Still needed:
- [x] create gzip archive of a full clone (full lfs-fetch) of the dmp repos
- [x] delete clones of dmp repos
- [ ] delete dmp repos from mskcc github
- [x] create a gzip archive of cmo-argos
- [x] follow procedure here for purging old cmo-argos repo changesets: https://docs.google.com/document/d/1Qj6pu4IsSB-a2YzdGZcDdc7Pht7s2ID8xS6WSCsSASw/edit#heading=h.u0dxaehidzbt

**Comment by sheridancbio** [comment]
We needed to split up the dmp-2022 repo archive (361GB compressed) into two pieces because our AWS access token for the msk AWS account is coded to expire after 1 hour. It takes about 45 minutes to transfer 180GB, so 2 pieces worked. Instructions were put in a README file which explains how to reconstitute the original tar file.
