### ISSUE TITLE
Barebones Test Import of GENIE Private 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1009]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
GENIE study imported 3-5x without disconnect

**Comment by sheridancbio** [comment]
Errors noted in the logs include:
- a "UnknownHostException" occurs in the import shell script log :
ResourceAccessException: I/O error on GET request for "http://oncotree.mskcc.org/api/tumorTypes": jxi2.mskcc.org; nested exception is java.net.UnknownHostException: jxi2.mskcc.org
This occurs because we specify in the JAR ARGS various proxy hosts which are not valid outside of the msk network :  http.proxyHost=jxi2.mskcc.org -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=draco.mskcc.org
>> for knowledgesystems-importer.cbioportal.org, these references must be dropped.

- imports are not possible because of the importer always reaching out to the internal mskcc network redcap server to probe whether or not clinical data needs to be fetched for the study. This probe always is performed .. even if "--disable-redcap-export" has been specified in the import script. So:
>> add the argument to the genie script
>> complete the story card which avoids the probe when using "--disable-redcap-export"

**Comment by sheridancbio** [comment]
We (Manda and I) imported genie_public on 2023_01_09 and it went in smoothly and quickly.

One needed followup step is to relocate the persistence caches for the genie portals into the knowledgesystems / public AWS account cluster. That way the caches can be reset after import is complete.

**Comment by sheridancbio** [comment]
4 test imports were completed without failure or error. Runtimes were consistent and significantly faster than imports from the msk AWS account:
16:59 -> 17:31 (runtime : 32 min)
18;58 -> 19:30 (runtime : 32 min)
23:46 -> 24:28 (runtime : 32 min)
05:50 -> 06:22 (runtime : 32 min)
