### ISSUE TITLE
Deidentify/Hide AGE_AT_SEQ Attributes

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1021]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Any AGE_CURRENT over 89 will be binned to >89 (no need to bin < 18).

AGE_AT_SEQ_REPORTED_YEARS over 89 will be binned to >89. Further de-identification may be required - see 5.

AGE_AT_SEQ_REPORTED_YEARS + OS_MONTHS will indicate a patients age. For any patient such that sum(AGE_AT_SEQ_REPORTED_YEARS + OS_MONTHS) > 89, we will cap AGE_AT_SEQ_REPORTED_YEARS such that sum(AGE_AT_SEQ_REPORTED_YEARS + OS_MONTHS) will never indicate a patients age over 89.

Example:

AGE_AT_SEQ_REPORTED_YEARS = 88
OS_MONTHS = 48

This patient is 92 years old.

We want to cap AGE_AT_SEQ_REPORTED_YEARS to ">84", which is the concatenation of the
string ">" and the number (AGE_AT_SEQ_REPORTED_YEARS - OS_MONTHS)

Note, it is possible if a consumer of this data looks at multiple snapshots of
AGE_AT_SEQ_REPORTED_YEARS for the same patient, they will be able to determine the
patients true age. While this case does exist and is something we should find a long term
solution for, it is not covered by the HIPAA safe harbor rule, so the above method is
satisfactory for the time being.

**Comment by sheridancbio** [comment]
One problem with the rules above is that a pediatric cancer patient who goes on as a cancer survivor above age 90 will be capped at a negative number .. such as ">-3". Since this makes no sense, I'll add a lower limit to the cap of 0.

Acronyms: 
- AASRY = AGE_AT_SEQ_REPORTED_YEARS
- OM = OS_MONTHS
- OY = OS_YEARS

Actually, I think the math above is a bit off. First, adding months to years is incorrect, so OM must first be converted to OY before computing the sum of AASRY + OY.
But also: the stated goal is to never have the sum of AASRY + OY to exceed 89. Using the logic above we would set AASRY(out) to be AASRY(in) - OY which would result in a patient who was sequenced at age 40 and who survived 50 years being being assigned AASRY(out) ">-10" which is too small. I think the intended formula is actually AASRY(out) = ">" + (90 - OY).

**Comment by sheridancbio** [comment]
PR for code under development is here:
https://github.com/knowledgesystems/cmo-pipelines/pull/986
