### ISSUE TITLE
Resolve Age At Seq > Age at Death

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1029]
## OUTCOME
**What is the motivation for this card? Link issue or bug here.**
Samples showing an age at seq that is higher than age at death (e.g. P-0074869)

- [x] add support inside DDP for age at seq
- [x] remove support inside CVR for age at seq
- [x] update redcap project files
- [x] make changes to redcap projects 
- [x] Don't forget to add `ddp.age_at_seq_date_filename=data_age_at_seq_date_ddp.txt` to `pipelines-configuration/properties/fetch-ddp/application.properties` 

**What is the "done" condition of this card?**
An understanding of why there are patients have higher age at seq than age at death - if resolvable within code, fix is applied. If data issue, proper people are notified to update it 

use ddp.mskcc.org to check samples/patients

### ACTION ITEMS (optional)
**List action items needed to achieve the "done" condition.**
- 
-    
-

**Comment by sheridancbio** [comment]
another example to check : P-0002755

**Comment by mandawilson** [comment]
Age at seq calculated here: https://github.com/knowledgesystems/cmo-pipelines/blob/64f4244d505ba8f58bdca7f91dc564e5efa05300/cvr/src/main/java/org/cbioportal/cmo/pipelines/cvr/CVRUtilities.java#L415

In this case patient died at age X.  Both samples were sequenced shortly before the patient died.  In one case, the sample was sequenced more than 1 year ago.  In the other, the sample was sequenced less than 1 year ago.  The reported age at sequencing of the first sample is X + 1.  The reported age at sequencing of the second sample is X + 2.  

And current age (X + 2 even though the patient died less than a year ago) is in this file: `dmp/mskimpact/ddp/ddp_age.txt`
NOTE: this calculated by today's year - the year they were born.  So for this patient it is X + 2, even though they died less than a year ago.

When age at sequencing is calculated it uses the age the patient would be today, and calculates the time since sequencing and then does Math.ceil(Integer.parseInt(patientAge) - diffYears).  Math.ceil is the second thing that is rounded.

For one sample it has been more than a year since sequencing, and for the other it has been less than a year.  In addition, the patient age reported is wrong.  Because there are two numbers here (age + age at seq) which are rounded up we get age at sequencing as X + 1 and X + 2.

Seq date is found in: `dmp/mskimpact/cvr/seq_date.txt`
