### ISSUE TITLE
Review and Create a Process Document

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1040]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Evaluate current issues with working process - come up with solutions or guidelines to reduce

**Comment by mandawilson** [comment]
I think it would help to decide on a documentation system and then really document everything.  Whatever the modern day wiki like thing is where you can link easily to other pages etc.  We can reference Google docs, but I don't think the system should be google docs.  And it should either be password protected or inside MSK so that we can comfortably say where files are located.
