### ISSUE TITLE
Resolve DDP Fetcher Auth Issue

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1128]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
DDP Pipeline can authenticate and run to completion

**Comment by sheridancbio** [comment]
The https connection to the ddp server was failing due to an updated ssl certificate deployed recently to the ddp server. It is suspected that the certifying authority signature was not trusted because it was not packaged into the java1.8 distribution of the JRE which is running the ddp server currently (which is 8 years old). We plan to soon update our java environment, but for the meantime we added the certificate from the server into the truststore file which we currently use for trusting AWS services (rds) and the msk redcap server. That truststore now includes the certificate for ddp (which expires 2024_07_08) and this PR adds the truststore argument to ddp fetches in our pipelines: https://github.com/knowledgesystems/cmo-pipelines/pull/1053
