### ISSUE TITLE
Confirm Germline Event Filtering Behavior for AZ

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1162]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Confirm that germline event filtering for data_mutations_extended.txt, data_mutations_nonsigned_out.txt, and data_sv.txt works as intended. If not, implement desired behavior

**Comment by callachennault** [comment]
General rule: Filter out all UNKNOWN events and all GERMLINE events that have a PATH_SCORE other than 'Pathogenic' or 'Likely pathogenic'. Here's how that looks out for the three files we're filtering:

- `data_mutations_extended`: Filter out all UNKNOWN events and all GERMLINE events that have a PATH_SCORE other than 'Pathogenic' or 'Likely pathogenic'
- `data_mutations_nonsigned_out.txt`: Doesn't contain a PATH_SCORE column because this file doesn't and will not contain GERMLINE events. This means all UNKNOWN events are filtered out.
- `data_sv`: Doesn't contain PATH_SCORE column because CVR does not have this data for SV (confirmed by Mihir). This means all GERMLINE and all UNKNOWN events are filtered out of the file.
