### ISSUE TITLE
Get All Themes onto Prod Keycloak

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#609]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Themes are up for MSK/SCLC/Triage/Private/Genie intranet portal

**For SCLC, we have to restore the link to the sclc registration google form.** 
https://docs.google.com/forms/d/e/1FAIpQLSeSVmkIV5jWwqpUYOGXdm_26mnltXfDYXioKMu0LLYvIXXbgA/viewform

Jul 8 - would like to add theme for AACR Genie intranet - basically a copy of the genie-private login page with cBioPortal logo swapped out for [AACR genie logo](https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/blob/master/keycloak/themes/genie-private-cbioportal/login/resources/img/aacr_logo.png) and any reference to "portal" changed to "website".  Also, we should link to a new "difficulties logging in" google doc (I will provide content).  Google signon will not be supported, only Synapse. -Benjamin

## Technical Description (How are we going to achieve the above)
Edit theme files inside portal-config repo and create docker images and those get pulled in

**Comment by sheridancbio** [comment]
Notes from Ben:

aacr-genie-internet realm --- wordpress internet site using our keycloak to authenticate

we want the same kind of login as for our genie login -- synapse and google
card #609

top logo : AACR project genie instead of cBioPortal
"before you can use this portal" --> "before you can use this website"
First time registration is still valid (talks about synapse)
If you have difficulties -->  a new google doc (could be empty now)
One button for login : SYNAPSE only

[this will have BPC users from genie private ... inserted into this realm --- Ben will do it]
-----------------
SCLC -- we need a link to the google sign up form referenced in the war file from before our move to keycloak. Request Access to the SCLC

Manager gets emails from the google spreadsheet ... she is going to manually manage the SCLC user updates .. not import script
