### ISSUE TITLE
Fix Missing Fusions in Archer Cohort

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#620]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Archer Cohort is missing fusions data -- done condition is that the data is available. 
## Technical Description (How are we going to achieve the above)
Will need to debug -- reason for missing data is not clear yet. Could be related to how it's imported or if there's a workaround that doesn't work.

**Comment by ao508** [comment]
Initial findings:


1. Study summary "Genomic Profile Samples Count" : "Molecular Profile" table populates on a matching stable id pattern and has some sort of conditional logic where "if mutations profile exists then also display fusion" going on.

MSKARCHER:
If stable id is "mskarcher_mutations" then the fusions profile shows up in the study summary table because the profile is imported as "mutations" with genetic alteration type "MUTATION_EXTENDED" and datatype "FUSION".

MSKIMPACT
Shows both mutations and fusions profiles and has both "mskimpact_mutations" and "mskimpact_fusion" genomic profiles. 

2. "Study summary "Structural Variant Genes" table likely populates based on whether a genomic profile exists with genetic alteration type "STRUCTURAL_VARIANT". 

MSKARCHER: If stable id is "mskarcher_mutations" and genetic alteration type = "STRUCTURAL_VARIANT" then Structural Variant genes table cannot be selected under charts. 

When stable id is "msarkcher_fusion" and genetic alteration type = "STRUCTURAL_VARIANT" you can select the "Structural Variant" genes table from the charts but it doesn't display anything.

**Comment by ao508** [comment]
work in progress: https://github.com/cBioPortal/cbioportal/pull/8774

**Comment by ao508** [comment]
PULL REQUESSST 🎉  

https://github.com/cBioPortal/cbioportal/pull/8774
