### ISSUE TITLE
Build out support in Importer + Import Scripts for All File Renamings

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#632]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Fully support (including backwards compatibility) for entire list of file renamings for the curation. 
Successful done condition is all scripts/codebases function the same regardless of old or new file names

Following is some information from Ramya about what is involved. We will want to do a full analysis of changes and search the source code for any side effects / special cases.

1. writingZScoresStagingFlie() - NO IMPORT ISSUE
• This function is called for protein_quantification and RPPA profiles to create zscores (through NormalizeExpressionLevels). This functionality has been removed for RNA-seq expression profiles.
• Exception will be thrown by the NormalizeExpressionLevels for protein_quantification and RPPA files as it looks for Hugo_Symbol or Entrez_ID in the file header and these two files will have only Composite_REF_Element in header.
• And though zscore creation during import fails, the zscore staging file from the folder gets imported.
• Can this functionality be removed for protein expression profiles?
1. ZSCORE_STAGING_FILENAME_SUFFIX variable - NO IMPORT ISSUE
• the suffix for zscore files currently is _Zscores.txt in https://github.com/knowledgesystems/pipelines/blob/a41b3bff48f7445ce47cbfbc9305bef8f7bc5a1a/importer/src/main/java/org/mskcc/cbio/importer/model/DatatypeMetadata.java#L64 and this variable is used in ImporterImpl.java and FileUtilsImpl.java
• Currently, the supported zscore suffixes are : _Zscores.txt, _zscores.txt, _zscores_ref_diploid_samples.txt and _zscores_ref_all_samples.txt
1. gene_matrix file - FAILS IMPORT for the new filename data_gene_panel_matrix.txt
• STABLE_ID is not required for gene matrix file https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#meta-file-13
• The old matrix file name is data_gene_matrix.txt and the importer doesn't require the STABLE_ID for it.
• For the new filename data_gene_panel_matrix.txt, importer is looking for a stable_id in the datatypes portal config sheet.
• Is there a check in the importer that tells it to not look for STABLE_ID for data_gene_matrix.txt file? and data_gene_panel_matrix.txt needs to be added to the list.
1. MAF issues - FAILS IMPORT for MSK isoform
• No reference to mskcc isoform MAF in the datatypes portal config sheet - File is not recognized for import.  
    new mskcc isoform filename data_mutations_mskimpact_transcripts.txt
• Uniprot isoform MAF is imported with no issues - data_mutations_uniprot_canonical_transcripts.txt.

**Comment by averyniceday** [comment]
Specifically backwards-compatible code that supports the new gene_matrix and maf renamings

**Comment by sheridancbio** [comment]
All renamings from the "Rename Data Files" spreadsheet (sheet "Finalized Name Changes List" were examined except for MRNA/expression files and data_SV (which were already handled in the last pass). Source code was searched for specific references to filename substrings from the affected patterns. The only filetype I identified as having logic based on the literal filename is the mutation (MAF) datatype. There are some references to filename patterns with "data_bcr_clinical..." but I believe that these references are obsolete and can be cleaned up.
The MAF filenames are mentioned through these symbolic constants:
  MUTATIONS_METADATA_FILENAME
  MUTATIONS_STAGING_FILENAME
  MUTATIONS_STAGING_MISC_FILENAME
  MUTATIONS_STAGING_MSKCC_FILENAME
  MUTATIONS_STAGING_UNIPROT_FILENAME
  MUTATION_STAGING_GENERAL_PREFIX

The GENERAL_PREFIX one seems to be one key place to add logic around.

**Comment by sheridancbio** [comment]
References to the MAF filename constants appear in:
importer/src/main/java/org/mskcc/cbio/importer/io/internal/FileUtilsImpl.java
importer/src/main/java/org/mskcc/cbio/importer/internal/ImporterImpl.java
importer/src/main/java/org/mskcc/cbio/importer/persistence/staging/StagingCommonNames.java
importer/src/main/java/org/mskcc/cbio/importer/model/DatatypeMetadata.java

The latter two are only definitions of symbolic constants, so we only need to examine / trace ImporterImpl and FileUtilsImpl.

**Comment by sheridancbio** [comment]
FileUtilsImpl.getCaseListFromStagingFile() will (for all mutation files based on GENERAL_PREFIX) try to find a list of sequenced samples from a file and return that before scanning the file to extract sample IDs. This must be expanded to include the new filename patterns.

ImporterImpl.loadCancerStudyStagingFiles() iterates over all source files for the data types and it specifically looks for mutation files with "uniprot" or "mskcc" depending on the overrides source that has been set. This must be expanded to look for the new patterns. We may need to make multiple calls to getImportFilenames() in this logic:
 499                         for (String filename : getImportFilenames(rootDirectory, cancerStudyMetadata, filenamePattern, false, createdClinicalFiles)) {
 500                             if (new File(filename).exists()) {

Later in the same function, we will annotate a MAF file, but detection must be expanded:
 535                     if (stagingFilename.endsWith(DatatypeMetadata.MUTATIONS_STAGING_FILENAME ) || stagingFilename.contains(DatatypeMetadata.MUTATION_STAGING_GENERAL_PREFIX)) {
 536                         getAnnotatedFile(stagingFilename, transcriptOverridesSource);
 537                         stagingFilename = importStatistics.getMafFilename();

**Comment by sheridancbio** [comment]
I've also scanned the cbioportal codebase looking for references to mutation filename literals and found none. The only references with "_mutation" are references to genetic profile names (in test code) and the various mutationType enum members (like "missense_mutation")

**Comment by sheridancbio** [comment]
After talking with @rmadupuri, I think there is an adjusted intention for the importer. Rather than maintain support for the old behaviors regarding MAF filenames, we want the importer to be adjusted to follow these rules:
- the importer will no longer annotate unannotated MAF files using uniprot canonical transcripts. Any annotation which occurs will be done with mskcc transcript selections (no matter what database destination or portal name is involved for this import)
- MAF filename pattern recognition is simplified: these patterns will be removed from the datatypes sheet:
```
   - data_mutations_extended.txt
   - data_mutations_extended_*.txt
   - data_mutations_extended_foundation.txt
   - data_mutations_mskcc.txt
   - data_mutations_uniprot_canonical_transcripts.txt
   - data_mutations_uniprot_canonical_transcripts_*.txt
   - data_mutations_uniprot_canonical_transcripts_foundation.txt
   - data_mutations_mskimpact_transcripts.txt
```
  a single datatype record for called mutation data files will be added with staging filename pattern: data_mutations*.txt which will be imported as a genetic profile with datatype MAF and genetic_alteration_type "MUTATION_EXTENDED".
- all files matching that pattern will be aggregated into a single genetic profile of type during import (allow for splitting of MAF files into parts, such as [data_mutations.txt, data_mutations_2.txt, data_mutations_3.txt, data_mutations_manual.txt, ...]
- additionally, a single datatype record for uncalled mutation data files will be added with staging filename pattern: data_mutations_uncalled.txt which will be imported as a genetic profile with datatype "MAF" and genetic_alteration_type "MUTATION_UNCALLED" . This will be an exception to the wildcard rule data_mutations*.txt.
- another exception to the wildcard rule data_mutations*.txt will be "data_mutations_uniprot.txt". If a file with this name is present, it will cause an error or warning for the study being imported and the content of this file will not be imported.
- our source data repositories will be updated : when studies were annotated both with mskcc transcripts and also uniprot transcripts, the file containing the uniprot transcripts will be dropped and the file containing the mskcc transcripts will be renamed data_mutations.txt (or something appropriate not containing the specifier string "mskcc"). If there are any studies which are only annotated with uniprot transcripts and for which we intend to maintain uniprot transcript annotations (for data stability to prior publications?) the uniprot transcript annotated MAF file will be renamed "data_mutations.txt" (or something appropriate and not matching "data_mutations_uniprot.txt")

**Comment by averyniceday** [comment]
drop transcripts override option from import-scripts

**Comment by sheridancbio** [comment]
Testing complete:
most testing done on set_strongv bic study
-----------------------------------
Test 8 permutations without mutations_uncalled:

- fusions
	- none
	- data_fusions.txt
- mutations - called
	- none at all
	- data_mutations_extended.txt
	- data_mutations.txt
	- data_mutations1.txt data_mutations2.txt data_mutations3.txt

=fusions+no_mutations good
=fusions+data_mutations_extended good
=fusions+ data_mutations good
=fusions+ data_muatation1,2,3 good
=no fusions + no mutations good
=no fusions + data_mutations_extended good
=no fusions + data_mutations good
=no fusions + data_mutations1,2,3 good
-----------------------------------
Test 3 cases with mutations_uncalled - 3 times (1st with no mutations, 2nd with data_mutations.txt, 3rd with data_mutations1/2/3)

- mutations - uncalled
	- none at all
	- data_mutations_uncalled.txt
	- data_mutations_uncalled1.txt data_mutations_uncalled2.txt

=no called + no uncalled (not tested - same as fusions + no mutations)
=no called + data_mutations_uncalled : good
=no called + data_mutations_uncalled1.txt + data_mutations_uncalled2.txt
=data_mutations.txt + no uncalled (not tested - same as fusions + data_mutations.txt)
=data_mutations.txt + data_mutations_uncalled.txt : good
=data_mutations.txt + data_mutations_uncalled1.txt + data_mutations_uncalled2.txt : good
=data_mutations1,2,3 + no uncalled (not tested - same as fusions + data_mutations1,2,3)
=data_mutations1,2,3 + data_mutations_uncalled.txt : good
=data_mutations1,2,3 + data_mutations_uncalled1.txt + data_mutations_uncalled2.txt : good
-----------------------------------
Test 9 permutations	(these tests examined only whether the data_gene_matrix data was imported or not ... in or not in the presence of gene panel files)

- gene-panel-matrix
	- none at all
	- data_gene_matrix.txt
	- data_gene_panel_matrix.txt
- gene-panel
	- none at all
	- data_gene_panel.txt
	- data_gene_panel_PANELNAME1.txt, data_gene_panel_PANELNAME2.txt
= none + none (not tested - same as fusions + data_mutations_extended)
= data_gene_matrix + none : good
= data_gene_panel_matrix.txt + none : good
= none + data_gene_panel.txt : good
= data_gene_matrix + data_gene_panel.txt : good
= data_gene_panel_matrix + data_gene_panel.txt : good
= none + data_gene_panel_impact468.txt : good
= data_gene_matrix + data_gene_panel_impact468.txt : good
= data_gene_panel_matrix + data_gene_panel_impact468.txt : good
-----------------------------------
Final test with brca_tcga study : good

**Comment by sheridancbio** [comment]
We believe we have reached a point where the importers function correctly if the new filename patterns are present (and we are mostly backwards compatible except for the change from data_mutations_extended_* to data_mutations* ... with the exclusion of data_mutations_mskcc and data_mutations_uniprot and the "carve out" so that data_mutations_uncalled* belong to the mutations_uncalled alteration type and everything else in data_mutations* belongs to the mutations_extended alteration type.

We have renamed some files which previously were not intended for import but which fell into the data_mutations* patern:
- data_mutations_nonsignedout.txt was renamed to data_nonsignedout_mutations.txt
- data_mutations_annotated.txt was renamed to data_annotated_mutations.txt (in lymphoma supercohort)

**Comment by sheridancbio** [comment]
The scripts are currently not compatible with the new filename patterns. Here is some of the remaining work needed:
Scripts which explicitly refer to filenames:

MUTATION FILENAME REFERENCES:

fetch-dmp-data-for-import.sh
	- cvr_consent_status_checker.py MSK_IMPACT_DATA_HOME/data_mutations_extended.txt
merge.py
	- MUTATION_FILE_PATTERN = 'data_mutations_extended.txt' (to recognize mutation files for merging)
oncokb-annotator.sh
	- SOURCE_MAF_FILE="$MSK_SOLID_HEME_DATA_HOME/data_mutations_extended.txt"
report-missing-clinical-records.py
	- MAF_GENERAL_FILE_PATTERN = 'data_mutations_extended.txt'
subset_and_merge_crdb_pdx_studies.py
	- MUTATION_FILE_PATTERN = 'data_mutations_extended.txt'
subset-impact-data.sh
	- grep -v "GERMLINE" $OUTPUT_DIRECTORY/data_mutations_extended.txt > $OUTPUT_DIRECTORY/data_mutations_extended.txt.tmp
test/resources/generate_case_lists/case_list_config.tsv
	- cases_cnaseq.txt        data_CNA.txt&data_mutations_extended.txt
test/resources/subset_and_merge_pdx/data_repos/datahub_source_repo/test_source_study_1/meta_mutations_extended.txt
	- test/resources/subset_and_merge_pdx/data_repos/datahub_source_repo/test_source_study_1/meta_mutations_extended.txt
test/test_subset_and_merge_pdx.py
	- orig_maf_copy = os.path.join(destination_directory, "orig_data_mutations_extended.txt")
test_if_impact_has_lost_allele_count.sh
	- sourcefilename=$MSK_IMPACT_DATA_HOME/data_mutations_extended.txt
generate_case_lists.py
	- MUTATION_STAGING_GENERAL_PREFIX = "data_mutations" (needs uncalled carveout/handler)
generate-missing-metafiles.py
	- MUTATION_STAGING_GENERAL_PREFIX = "data_mutations" (needs uncalled carveout/handler)
test/test_merge_script.py
	- './test/resources/merge_studies/temp_standard_merge/data_mutations_extended.txt': 70, (test cases should be added with new filename patterns)

MERGE SCRIPT ISSUES

filenames are recognized and categorized into datatypes which correspond to a mapping between a meta filename and a data filename

current supported meta:data filename mappings:
'meta_timeline.txt' : 'data_timeline.txt' --- filetype is 'timeline'
'meta_CNA.txt' : 'data_CNA.txt' --- filetype is 'cna'
'meta_SV.txt' : 'data_SV.txt' --- filetype is 'structural_variant'
'meta_gene_matrix.txt' : 'data_gene_matrix.txt' --- filetype is 'gene_matrix'
'meta_methylation_hm27.txt' : 'data_methylation_hm27.txt' --- filetype is 'methylation_hm27'
'meta_methylation_genebodies_hmEPIC.txt' : 'data_methylation_genebodies_hmEPIC.txt' --- filetype is 'methylation_genebodies_hmEPIC'
'meta_fusions.txt' : 'data_fusions.txt' --- filetype is 'mutations'
'meta_methylation_promoters_wgbs.txt' : 'data_methylation_promoters_wgbs.txt' --- filetype is 'methylation_promoters_wgbs'
'meta_clinical.txt' : 'data_clinical.txt' --- filetype is 'clinical'
'meta_clinical_patient.txt' : 'data_clinical_patient.txt' --- filetype is 'clinical_patient'
'meta_mutations_extended.txt' : 'data_mutations_extended.txt' --- filetype is 'mutations'
'meta_RNA_Seq_expression_median.txt' : 'data_RNA_Seq_expression_median.txt' --- filetype is 'RNA_Seq_expression_median'
'meta_methylation_promoters_hmEPIC.txt' : 'data_methylation_promoters_hmEPIC.txt' --- filetype is 'methylation_promoters_hmEPIC'
'meta_expression.txt' : 'data_expression.txt' --- filetype is 'expression'
'meta_fusions_gml.txt' : 'data_fusions_gml.txt' --- filetype is 'fusions_gml'
'_meta_cna_hg19_seg.txt' : '_data_cna_hg19.seg' --- filetype is 'segment_hg19'
'meta_methylation_hm450.txt' : 'data_methylation_hm450.txt' --- filetype is 'methylation_hm450'
'meta_methylation_genebodies_wgbs.txt' : 'data_methylation_genebodies_wgbs.txt' --- filetype is 'methylation_genebodies_wgbs'
'meta_clinical_sample.txt' : 'data_clinical_sample.txt' --- filetype is 'clinical_sample'
'_meta_cna_hg18_seg.txt' : '_data_cna_hg18.seg' --- filetype is 'segment_hg18'
'meta_log2CNA.txt' : 'data_log2CNA.txt' --- filetype is 'log2CNA'
'meta_rppa.txt' : 'data_rppa.txt' --- filetype is 'rppa'

not supported, probably need to support (^^ means also doesn't support old filename ... maybe these get swept up into "other"):
'meta_mutations.txt' : 'data_mutations*.txt'
'meta_gene_panel_matrix.txt' : 'data_gene_panel_matrix.txt'
'meta_cna.txt' : 'data_cna.txt'
'meta_linear_cna.txt' : 'data_linear_cna.txt' ^^
'meta_log2_cna.txt' : 'data_log2_cna.txt' ^^
'meta_cna_consensus.txt' : ''data_cna_consensus.txt' ^^
'meta_cna_rae.txt' : 'data_cna_rae.txt' ^^
'meta_cna_foundation.txt' : 'data_cna_foundation.txt' ^^
'meta_armlevel_cna.txt' : 'data_armlevel_cna.txt' ^^
'meta_rppa_zscores.txt' : 'data_rppa_zscores.txt' ^^
'meta_mirna.txt' : 'data_mirna.txt' ^^
'meta_sv.txt' : 'data_sv.txt'
'meta_methylation_promoters_hmepic.txt' : 'data_methylation_promoters_hmepic.txt'
'meta_methylation_genebodies_hmepic.txt' : 'data_methylation_genebodies_hmepic.txt'
there are a variety of mrna expression names, data_mrna_affymetrix_microarray.txt instead of data_expression.txt, but also:
    - data_mrna_affymetrix_microarray_zscores_ref_diploid_samples.txt
    - data_mrna_agilent_microarray.txt
    - data_mrna_seq_rpkm.txt
    ... a total of 34 mrna filename patterns, each with their own meta filename version

not supported, and don't plan to support:
data_bcr_clinical_data_patient.txt
data_bcr_clinical_data_sample.txt
