### ISSUE TITLE
Spin up new cluster + pipelines node

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#665]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)

- [x] New Cluster is available with 1000+ IPs available
- [x] Spin up new pipelines node
- [x] We can run kubectl here
- [x] Have a db 

## Technical Description (How are we going to achieve the above)
Use ADO Pipeline - then apply some of the deployment yaml files we have
Run the setup scripts

**Comment by mandawilson** [comment]
- [x] Change size of pipelines to r5.4xlarge

**Comment by mandawilson** [comment]
```
[cbioportal_importer@ip-10-1-141-114 ~]$ ssh-add ~/.ssh/id_rsh_github_com 
Identity added: /home/cbioportal_importer/.ssh/id_rsh_github_com (/home/cbioportal_importer/.ssh/id_rsh_github_com)
[cbioportal_importer@ip-10-1-141-114 ~]$ ssh-add ~/.ssh/id_rsh_github_mskcc_org 
Identity added: /home/cbioportal_importer/.ssh/id_rsh_github_mskcc_org (/home/cbioportal_importer/.ssh/id_rsh_github_mskcc_org)
```

**Comment by mandawilson** [comment]
The git clone commands are not working as they are (using ssh).  I can clone the public repos when using https.  I was assuming it would work on the previous eps pipelines, but it doesn't:

```
[cbioportal_importer@ip-10-1-21-42 test-ssh-github-tmp]$ env GIT_TRACE=1 GIT_CURL_VERBOSE=1 git clone --verbose  git@github.com:cBioPortal/cbioportal.git 
09:11:12.238990 git.c:440               trace: built-in: git clone --verbose git@github.com:cBioPortal/cbioportal.git
Cloning into 'cbioportal'...
09:11:12.261567 run-command.c:663       trace: run_command: unset GIT_DIR; ssh git@github.com 'git-upload-pack '\''cBioPortal/cbioportal.git'\'''
ssh_exchange_identification: read: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Github no longer allows username + password authentication so we either need to login and get a token or get the ssh setup working.  I tried to login to the GitHub.com account but it has 2 layers of security and so I couldn't get the authentication code because I can't login to the email address that it was sent to.  After that I didn't bother to try to login to the GitHub.mskcc.org account.

**Comment by mandawilson** [comment]
The mercurial repos are being cloned ... as of 9:33am EST 57G have been downloaded:
```
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ du -h
...
57G	.
```

```
[cbioportal_importer@ip-10-1-141-114 cbio-portal-data]$ ps -ef | grep clone
cbiopor+  3269  3110  0 10:00 pts/0    00:00:00 sh clone_repositories.sh
```
