### ISSUE TITLE
Get Imports Working 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#711]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Have CVR fetch working -- current exception is a NPE
`ERROR org.springframework.batch.core.step.AbstractStep - Encountered an error executing step mutationStep in job cvrJob`
java.lang.NullPointerException

**Comment by averyniceday** [comment]
1) CVR Consent Status Checker Fails -- identified problem as syntax error on new arguments (easy)

2) NPE during the CVR Fetch of heme -- unsure what is causing it but it errors out in CVRUtilities.buildMutationRecord when doing something like normal_ad - normal_dp (run a CVR fetch to get an actual JSON to test with)

3) NPE during import of CURRENT (non-new) impact study with `java.lang.NullPointerException: Sample is not found in database (is it missing from clinical data file?): P-0065108-T03-IH3` -- but I don't know the cause of this

**Comment by sheridancbio** [comment]
We had a successful import (aside from independent issues during the dmp merge and import) on 2021-10-19/20.

There was an issue with the CVR consent status checker script. It was corrected with:
https://github.com/knowledgesystems/cmo-pipelines/pull/897
https://github.com/knowledgesystems/cmo-pipelines/pull/898
However, this revealed another problem - we require access to port 9890 on host draco.mskcc.org, but this port had not been opened in the firewall to msk from our AWS subnet. This was requested and implemented by Franklin. After that the cvr_consent_status check seemed to be functioning again.

The NPE exception in the hemepact fetch was traced to the deserialization of the downloaded json file from cvr. There was a problematic sample (P-0056996-T02-IH3) with an event which was delivered with a defined field "normal_ad" but a null field "normal_dp", and that was generating a NullPointerException when creating representations of mutation events from this download. It was noticed that running cvr_fetch in test mode (-t) succeeded without exception even though the same condition was present in the downloaded cvr_data.json as before. This seems to mean that the downloaded json file is only deserialized for the requeue sample from master list step. In any case, the solution we adopted was to report the problematic sample to cvr and to put a consume step into the fetch-cmo-impact data step just before the cvr_fetch so that this sample would not be pulled during the fetch. This can be removed when the dmp cvr team corrects the data problem.

The NPE occurring during import was traced to 117 sample identifiers which were present in the hemepact #sequenced_samples header in data_mutations_extended.txt but not present anywhere else in the hemepact study, including (importantly) the clinical data from redcap and from the cvr fetch itself. We believe this state occurred because of a successful germline fetch combined with a failed tumor sample fetch for hemepact. Perhaps these tumor identifiers are referenced in downloaded hemepact germline sample records and got incorporated that way. The fix was to remove the references to these samples from data_mutation_extended's headers manually and check that back in the to dmp-2021 repository. We also should consider modifying the code so that a failed tumor sample fetch causes the germline fetch to be skipped.

Log files were also examined [script / importer / cvr fetcher] and a summary of remaining (non-fatal) error reports was captured.
