### ISSUE TITLE
On Demand Triage Importer

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#760]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Curators can import data into triage portal via manually run of triage importer jar from anywhere, including laptop.

shared SSH keypair for curation team to touch a file to trigger the job

**Comment by sheridancbio** [comment]
@mandawilson : I have added comments to the source code as discussed.

Another task on the todo list was to make a README describing how to build/deploy the executable tool, but rather than do that I have done 2 things:
- added configuration (the maven-ant-run plugin) to the root pom.xml of cmo-pipelines so that during mvn install the c++ compile step is performed (via the makefile). Also, I added configuration to delete the compiled binary during mvn clean.
- altered the buildproductionjars.sh script to deploy the built import-tool binary after the cmo-pipelines sources are built

I'll hold off merging the PR until you get a chance to look at the POM changes. I've done test builds in eks and this passes Jenkins.
