### ISSUE TITLE
Clear Cache for Genie and Public

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#777]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Caches clear after import
## Technical Description (How are we going to achieve the above)
Now that the jobs run on a different machine, the restart cache command does not access the right cluster for restart. We can see if some of the built in cacheclearing functions would work (there's also a api for clearing cache I think) -- or we can update scripts to switch between clusters before calling commands

**Comment by sheridancbio** [comment]
Initial planning for this card:
We have different authentication mechanisms for the two clusters - the "login" script uses the PingID authentication with a SAML tool which launches a docker image to let us obtain the needed authentication info and inject it into our aws configuration file. @averyniceday suggested that if we set up the kube/config file properly we may be able to simultaneously support 2 contexts ... one which would have a (relatively static) set of credentials for accessing the Knowledgesystems/public AWS cluster and one for using the PingID authentication to eks. I guess that would be best, but it may lead to confusion when we go onto the pipeline3 node and want to use the kubectl client to examine/manage running pods but we are shown the public/genie kubernetes cluster pods because we left the account pointing to the other context as the current context. If we follow this approach, we should adopt the practice of always specifying the context as part of the command line arguments to kubectl ... or scrupulously switching the context back to the default eks cluster context after doing what we need to do on the public cluster (i.e. wiping the persistence cache).
The other (perhaps safer) option is to leave the eks configuration as it is .. defaulting to the eks cluster with only a single context. Then we create a separate aws configuration file and a separate kube/conf file. When we want to issue commands to the public cluster we use command line options to force the reading of the separate files (which should be fairly constant because we don't change the public credentials often)

**Comment by sheridancbio** [comment]
This was deployed to both the pipelines server and the eks pipelines node. A correction was added so that the script as written would run in either location.
https://github.com/knowledgesystems/cmo-pipelines/pull/922
https://github.com/knowledgesystems/cmo-pipelines/pull/923
