### ISSUE TITLE
Refresh Cache Regularly during a Long Import

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#779]

**Comment by sheridancbio** [comment]
The approach taken was a frequently running bash script which detected any modifications to the cancer_study table, followed by either a per-study cache clearing using the api cache endpoint in the portal, or by the kubernetes full cache reset script. After work was mature, the per-study cache update option became unworkable because of performance issues in production for the api cache endpoint. However, that functionality is in the script in case the performance issues are addressed.
https://github.com/knowledgesystems/cmo-pipelines/pull/925

**Comment by sheridancbio** [comment]
Performance in production seems good. In a testing deployment (running every 10 minutes instead of every minute) we saw this timeline:
04:00 beginning of public importer run
04:32 import of skcm_tcga beginning
07:05 import of skcm_tcga completed
07:20 [initial run] - redis caches cleared
07:28 import of skcm_tcga beginning
07:40 import of skcm_tcga completed
07:50 redis caches cleared
08:03 import of skcm_tcga beginning
09:44 import of skcm_tcga completed
09:50 redis caches cleared
10:07 import of skcm_tcga beginning
10:13 import of skcm_tcga completed
10:20 redis caches cleared
10:35 import of skcm_tcga beginning
10:50 import of skcm_tcga completed
10:50 redis caches cleared
