### ISSUE TITLE
Remove References to Fusions Inside cmo-pipelines (IMPACT CVR) *Needs Finalized File Format

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#788]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Cmo-pipelines uses SV instead of Fusions
## Technical Description (How are we going to achieve the above)
We have scripts like archer-fusions which merge fusion events - discuss and implement changes if necessary. If there are multiple scripts/data issues to consider, rediscuss and break into smaller cards

CVR Pipeline
https://github.com/knowledgesystems/cmo-pipelines/pull/929

Import-Scripts
https://github.com/knowledgesystems/cmo-pipelines/pull/931

- [ ] update PRs to write out specific header names once finalized by curators
## Potential Issues
Not sure if SV is a true substitute with fusions
### Outside People/Teams
Angelica, curation

**Comment by sheridancbio** [comment]
a survey of the import-scripts directory showed files which refer to fusions. Here are things that need to be addressed:

- [x] need to rework the archer_fusions_merger.py script, and direct events to SV file rather than a mutations file
	- get_existing_fusions()
	- get_archer_fusions()
	- update_fusions_file()
	- merge_fusions()
- [x] case_list_config.tsv makes references to the fusions files. This file is used inside generate_case_lists.py ... so maybe fusion files (if they exist) are scanned for cases during case list generation. subset_and_merge_crdb_pdx_studies.py also makes reference to the CASE_LIST_CONFIG_FILE through an environment variable. So this data file must be updated to drop fusions. (MEW: but probably add data_sv.txt)
- [x] fetch-dmp-data-for-import.sh calls archer_fusions_merger.py ... it should be changed to call a script which reformats the detected archer fusions as SV records. Also, change the git log message text for this step. Actually these two steps (calling the script and the log message) are done twice : once for impact and once for hemepact
- [x] There is also a mysql hack to change the imported profile to be a mutations datatype: "mysql update genetic_profile set genetic_alteration_type = 'MUTATION_EXTENDED' where genetic_alteration_type = 'FUSION' and stable_id = 'mskarcher_mutations'" .. this can be dropped
- [x] merge.py (luckily, fusions are "normal" rather than profile, so we probably can just drop references
	- drop FUSION filename pattern variables (and references) .. note : FUSION_META_PATTERN and FUSIONS_GML_META_PATTERN
	- update SV_FILE_PATTERN to lower case
- [x] `oncokb-annotator.sh` the oncokb-annotator script annotates fusions ... maybe this needs to be changed to process structural variants
- [x] report-missing-clinical-records.py - it refers to FUSION as a normal type of profile to check ... change this to structural variant (we may need to find the sample id column if it has a different header) (MEW: yes in fusions it is `Tumor_Sample_Barcode` and we have `Sample_Id` now)
- [x] subset_and_merge_crdb_pdx_studies.py : we can drop references to FUSIONS and we should update the SV_FILE patterns to lowercase filenames
- [x] `precache-portals.py`

- [ ] any `data_fusion.txt` files and meta files need converting to sv.

**Comment by averyniceday** [comment]
Query for pulling out Fusion studies for conversion for Anusha

`select cancer_study_identifier, genetic_profile.stable_id, import_date, genetic_profile.genetic_alteration_type, genetic_profile.datatype  from cancer_study inner join genetic_profile on genetic_profile.cancer_study_id = cancer_study.cancer_study_id where genetic_profile.datatype like '%fusion%'`

Google Sheets to track columns and conversion rules
https://docs.google.com/spreadsheets/d/1ymxedGZkisXywx2AvOjmlZ3ksOdKj8p3twb0010NxAE/edit#gid=0

**Comment by averyniceday** [comment]
Plan of Attack
- [x] 1. Remove regular fusion step from CVR and test. Want to see SV written out and no fusion file, but still a FML fusion file.
- [ ] 2. Add an SV_STATUS flag - test that written out with SOMATIC as value
- [ ] 3. redirect GMLFusion records into same written SV file, written out with GERMLINE as value
- [ ] 4. If necessary, add logic that inverses the record (discuss with Ino)

**Comment by mandawilson** [comment]
For the `archer_fusions_merger.py` script we need to change the variable names and text in the methods Rob mentions above.  We also need to:

- [ ] Reformat data_fusion.txt files into data_sv.txt files for the `existing_fusions` and make sure that the new data_sv.txt file that we are merging in has the same format.
- [x] Modify the `get_fusion_event_key(line)` method -- the key for a fusion is currently defined as `Tumor_Sample_Barcode` + `Fusion` + `Hugo_Symbol`.  Someone needs to define the new key.  It will be `Sample_Id` + ??? -- probably not just `Site1_Gene` maybe also `Site2_Gene` and what about `Site1_Pos` and `Site2_Pos`?  What about `Site1_Chrom` and `Site2_Chrom`?  What replaces the `Fusion` field?  We decided on `Sample_Id` + `Event_Info` + `Site1_Gene` + `Site2_Gene`

That is all that is needed for the `archer_fusions_merger.py` to work correctly.

- [x] We modified the parameters to `archer_fusions_merger.py` and so wherever we call this we need to modify them.

- [x] It is possible that `generate_case_lists.py` line 186 needs updating to check for `Sample_Id` and not just `SAMPLE_ID` and `Tumor_Sample_Barcode` or it should do case insensitive checks.  

- [ ] Add data_sv.txt and remove data_fusions.txt to `/data/portal-cron/git-repos/pipelines-configuration/resources/case_list_config.tsv`.

- [ ] Rename `$MSK_ARCHER_UNFILTERED_DATA_HOME/cvr/mapped_archer_fusion_samples.txt` -> `$MSK_ARCHER_UNFILTERED_DATA_HOME/cvr/mapped_archer_samples.txt`

- [x] Rename `$MAPPED_ARCHER_FUSION_SAMPLES_FILE` -> `$MAPPED_ARCHER_SAMPLES_FILE`

- [ ] Rename all `data_SV.txt` and `meta_SV.txt` to `data_sv.txt` and `meta_sv.txt`

**Comment by mandawilson** [comment]
- [x] ./import-scripts/test/resources/subset_and_merge_pdx/data_repos/datahub_source_repo/test_source_study_1/meta_fusions.txt
