### ISSUE TITLE
Debug Missing Alteration Enrichments 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#832]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
https://github.com/cBioPortal/cbioportal/issues/9366

**Comment by mandawilson** [comment]
The problem is that profiled samples are being counted twice.  The code first counts all samples with an associated gene panel (which the mutations and cna samples have in the msk_impact_2017 case).  The gene panel samples are not double counted because they are saved in a map with the key study_id+sample_id.  Then any samples profiled without a gene panel are counted.  This is the case for structural_variant profiled samples.  They are actually the same set of samples so this is how they are being double counted.  We think the solution is to make sure that sample_profile has a gene panel id set -- we think this means a third column in data_gene_panel_matrix.txt.

`ProfiledCasesCounter.java` loops through each gene in the alteration counts, if the gene is in a gene panel, it gets the number of cases with data in the gene panel and adds that to totalProfiledSamples.  Then it does this: `totalProfiledSamples += casesWithoutPanelData.size()` which adds all the structural variant cases (double counting).

**Comment by mandawilson** [comment]
Hack to fix this was:
```
INSERT INTO sample_profile (SAMPLE_ID, GENETIC_PROFILE_ID, PANEL_ID) SELECT sample.INTERNAL_ID, 17166, sample_profile.PANEL_ID FROM sample
    INNER JOIN patient ON sample.PATIENT_ID = patient.INTERNAL_ID
    INNER JOIN cancer_study ON patient.CANCER_STUDY_ID = cancer_study.CANCER_STUDY_ID
    LEFT JOIN genetic_profile ON cancer_study.CANCER_STUDY_ID =
genetic_profile.CANCER_STUDY_ID
    LEFT JOIN sample_profile ON sample_profile.GENETIC_PROFILE_ID = genetic_profile.GENETIC_PROFILE_ID AND sample.INTERNAL_ID = sample_profile.SAMPLE_ID
    LEFT JOIN gene_panel ON sample_profile.PANEL_ID = gene_panel.INTERNAL_ID
WHERE         genetic_profile.STABLE_ID = 'msk_impact_2017_mutations'
```
