### ISSUE TITLE
Confirm Duplicates and Introduction Date

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#847]
## Client (Who is making the request)
Per Ino: 
```
there seem to be a bunch of duplicate CDKN2A calls in the latest data_mutations_extended.txt   file from dmp-2022. Henry just reported it. 
```
![image.png](https://images.zenhubusercontent.com/5df39fc0f51fae8b1f448ec0/2bf865e5-94aa-404b-b932-3940b101e22b)

**Comment by sheridancbio** [comment]
Duplications confirmed. about 2200 whole-row duplications in mskimpact primary cohort. And 2700 in msk_solid_heme. Nearly all dmp studies/cohorts have some duplicates (except raindance).

Duplicates have been present since at least as far back as 2018 (counts decrease as you co back in time, but there were still several hundred in 2018)

Ino suggested checking for duplicates based on the unique index fields as well (rather than whole row)

If we want code to remove duplicates in primary cohorts, we would need to introduce that. We also would need code in the merge scripts to avoid creating new duplications during merge.
