### ISSUE TITLE
PDX Pipeline Followup

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#935]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Confirm PDX pipeline is working and importing main subsets (e.g. mixed_pdx_msk)

**Comment by sheridancbio** [comment]
Commands and filenames we used (Manda and I):
git checkout c4c0da1e4c2142aa705245b76265dcc0fa0ce750
cp -a data_SV.txt ~/svrollout/mskimpact/data_SV_unmodified_june30.txt
... (all 4 cohorts)
git checkout master
cp data_sv.txt ~/svrollout/mskimpact/data_sv.txt
... (all 4 cohorts)
../repopulate_class/apply_data_sv_updates_modified_for_old_sv_schema.py data_SV_unmodified_june30.txt > data_SV_with_eventinfo_corrections.txt 2> data_SV_with_eventinfo_corrections.log
... (all 4 cohorts)
python ../repopulate_class/backfill_class.py data_sv.txt data_SV_with_eventinfo_corrections.txt > data_sv_with_backfilled_class_field.txt
... (all 4 cohorts)
cut -f 1,23 data_sv_with_backfilled_class_field.txt | sort | grep -v TRANSLOCATION | grep -v INVERSION | grep -v DELETION | grep -v INTRAGENIC_LOSS | grep -v DUPLICATION | cut -f 2 | sort | uniq -c # this checks whether all filled in values have been excluded from the "missing value" set
cut -f 1,23 data_sv_with_backfilled_class_field.txt | sort | grep -v TRANSLOCATION | grep -v INVERSION | grep -v DELETION | grep -v INTRAGENIC_LOSS | grep -v DUPLICATION | cut -f 1 | sort | uniq > samples_missing_class_for_some_sv_event.ids
... (all 4 cohorts)

**Comment by sheridancbio** [comment]
A few studies were successfully updated over night last night:
mixed_pdx_ntrk
mixed_pdx_janjigian
mixed_aac

Remaining problems captured on Aug 30:

Most failures seem to be related to missing "case_lists" subdirectories in the study directories. These studies failed to import because of that:
mixed_pdx_rudin
mcc_pdx
mixed_pdx_kung
mixed_pdx_chiosis
mixed_pdx_scaltriti
mixed_gyn_pdx
mixed_pdx_singer
mixed_pdx_head_and_neck
mixed_gyn_pdx_rosen
mixed_pdx_lowe
prostate_pdx_scher
breast_pdx_chandarlapaty
mixed_pdx_cheung
mixed_pdx_somwar
mixed_pdx_abou_alfa
And there were these other causes for failures:
melanoma_pdx_rw (Caused by: java.lang.IllegalArgumentException: melanoma is not a supported cancer type.)
mixed_pdx_msk (Caused by: java.lang.NullPointerException: Sample is not found in database (is it missing from clinical data file?): P-0012443-T01-IM5)
colorectal_pdx_larson (Caused by: java.lang.IllegalArgumentException: colorectal is not a supported cancer type.)

**Comment by sheridancbio** [comment]
Problems related to imports reported to pdx team ... ball is in their court to do data corrections.
