### ISSUE TITLE
Cache Clearing on Public Portal 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#937]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Understand and fix Aaron's issue with e2e tests relating to caching
Change db strings for weekly db dumps

**Comment by sheridancbio** [comment]
I have traced the logic of the cache clearing script clear-persistence-caches-for-changed_studies.sh, and this script (which runs every minute) already is using the correct database name (which is cgds_public_release_5_0_0) because it extracts the database name from the configmap for the public portal and that file is up to date to what is in production.
