### ISSUE TITLE
Genie Import Support

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#985]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
The updated genie_public study has been imported to the database and is available on the genie portal.

## Technical Description (How are we going to achieve the above)
Failures reported during import mention JDBC Rollback. We will investigate an work out problems if possible. While doing that we will pursue a parallel track where the genie database is cloned (dumped/loaded) into the eks cluster and an import occurs there. Then the resulting database will be dumped/loaded back to the production database.

### cleanup tasks
- [ ] shut down genie-database-import-utility-node in public aws cluster

**Comment by sheridancbio** [comment]
Confirmed (from importer.properties) that the public genie database is hosted on rds node cbioportal-genie-db.cq26ederqvxp.us-east-1.rds.amazonaws.com (located in public knowledgesystems aws account).
Automated genie import shut down and snapshot of database node taken.

**Comment by sheridancbio** [comment]
The node genie-database-import-utility-node has been running for 6 months. It is a small node (actually t2.micro) .. but it still should be shut down when not needed. I will add a todo item to this card to shut it down at the completion of this work.

**Comment by sheridancbio** [comment]
We (Manda, Calla, I) discussed the approach planned. We recalled the fact that inside the msk provisioned aws account we observed similar disconnects in the import pipelines when the database server (rds) was not local to the import machine. We speculated that this might be due to a network routing configuration which routes all traffic (even rds<->ec2 traffic within the same account and same subnet) through the msk firewall and network security layer. If that is so then there would be no way to avoid possible network latency which could disrupt a mysql connection causing rollback.

So instead of bringing the data to the importer, we decided it would be more certain for us to bring the importer to the data .. deploying an importer to a standalone ec2 instance inside the knowledgesystems aws account.

**Comment by sheridancbio** [comment]
a user account (cbioportal_importer) was added to the node genie-database-import-utility-node and the basic importer paths were created as belonging to that user. However, this will not work on this node because it has only 1GB of available RAM, and the importers require much more. Our current production importer node (pipelines3) is of class r5.4xlarge, which has 128GB of available RAM. For this singe genie import run I will attempt to do it on a r5.2xlarge node (64GB RAM) ... because we can control here so that only a single import process is running at any given time.

**Comment by sheridancbio** [comment]
I wanted the importer node to be in the same subnet as the database node. This is not straightforward because the rds node knows its subnet group .. but the chosen subnet from the group is not reported. It required me to go into a node in the cluster and use the `host` command to get the ip address and then compare it to the subnet CIDR blocks to identify which subnet it was currently in. The rds node was in the CIDR block 172.31.80.0/20, which is in subnet subnet-3eb8a111 of the databases VPC.

**Comment by sheridancbio** [comment]
While a second manual run ran in the background the created node was set up as a pipelines importer node, running setup scripts in the repo/directory : portal-configuration/eks-cluster/pipelines.
One bugfix was needed : https://github.mskcc.org/knowledgesystems/portal-configuration/pull/8 and the maven tool install step failed because of lack of availability on the maven mirrors. This will be returned to and the setup of the node will be completed, for possible use early next week to import genie version 13, and for future uses as well.

To maximize chances of the genie import run succeeding we disabled the dmp/argos/cmo nightly import run last night, and the import did indeed succeed. Normal import pipeline scheduling has been resumed.

**Comment by sheridancbio** [comment]
We will return to this work soon as part of a follow-up task to import the update to genie-13-bpc. As the genie_public study has now been successfully imported, this card is complete.
